version: '3'

services:
    postgres-db:
        image: postgres:9.4
        container_name: camunda_postgres
        ports:
            - '8050:5432'
        environment:
            POSTGRES_USER: camunda
            POSTGRES_PASSWORD: camunda
            POSTGRES_DB: camunda_db
        restart: unless-stopped #always         
    camunda:
        image: camunda/camunda-bpm-platform:7.8.0
        container_name: camunda_bpm
        ports:
            - '8051:8080'
        environment:
            DB_DRIVER: org.postgresql.Driver
            DB_URL: jdbc:postgresql://postgres-db:5432/camunda_db?autoReconnect=true
            DB_USERNAME: camunda
            DB_PASSWORD: camunda
        depends_on:
            - 'postgres-db'
        restart: unless-stopped #always     